"use client";

import { useState } from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import { Profile } from "./types/profile";
import { AuthContext } from "./context/AuthContext";
import { SidebarContext } from "./context/SidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [userData, setUserData] = useState<Profile | null>(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isOpen, setIsOpen] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext.Provider
          value={{ isAuthenticated, setIsAuthenticated, userData, setUserData }}
        >
          <SidebarContext.Provider value={{ isOpen, setIsOpen }}>
            {children}
          </SidebarContext.Provider>
        </AuthContext.Provider>
      </body>
    </html>
  );
}
